on: [push]
  
jobs:
  sigma_code_scanning_run_steps:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
  
      - name: SIGMA analysis
        run: sigma analyze --format sarif .
  
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: sigma-results.json
