on: [push]
  
jobs:
  sigma_code_scanning_run_steps:
    runs-on: ubuntu-latest
    container:
      image: docker.io/sigsynopsys/sigma-release-image:latest
      credentials:
        username: ${{ secrets.DOCKERHUB_SIGSYNOPSYS_USERNAME }}
        password: ${{ secrets.DOCKERHUB_SIGSYNOPSYS_PASSWORD }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
  
      - name: SIGMA analysis
        run: sigma analyze --format sarif .
  
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: sigma-results.json
